pipeline {
    agent any

  environment {
      //TERRAFORM_HOME = tool name: 'Terraform', type:'com.cloudbees.jenkins.plugins.customtools.CustomTool'
      KOPS_HOME = tool name: 'kops', type:'com.cloudbees.jenkins.plugins.customtools.CustomTool'
      AWS_CLI_HOME = tool name: 'aws-cli', type:'com.cloudbees.jenkins.plugins.customtools.CustomTool'
  }
    stages {
        stage('KOPS_Install') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'patch-1', url:'https://github.com/sunilgupta01/infra.git'

                // Run Maven on a Unix agent.
                //sh "mvn -Dmaven.test.failure.ignore=true clean package"
                // print (env.KOPS_HOME)
                configFileProvider([configFile(fileId: 'id_rsa.pub', variable: 'ssh_pub_key')]) {
                    sh """#! /bin/bash
                       set -x
                       export PATH=$PATH:$KOPS_HOME:$AWS_CLI_HOME
                       #which kops
                       ls -latr
                       aws s3api create-bucket --bucket ${BUCKET_NAME} --region ${REGION} --no-cli-pager
                       aws s3api put-bucket-versioning --bucket ${BUCKET_NAME} --versioning-configuration Status=Enabled --no-cli-pager 
                       echo kops name  $CLUSTER_NAME
                       kops create -f kops/cluster.yaml
                       kops create secret --name ${CLUSTER_NAME} sshpublickey admin -i $ssh_pub_key
                       kops update cluster ${CLUSTER_NAME} --yes --admin
                       kops validate cluster ${CLUSTER_NAME} --wait 10m
                    """

                }
            }
        }
    }
}
